markdown: kramdown
permalink: pretty
baseurl: ''

paginate: 5
paginate_path: "/page:num/"

safe: false
gems: [jekyll-paginate, jekyll-feed]

collections:
 vehicles-for-rent:
  output: true
  permalink: /services/vehicles-for-rent/:title
  
 ticketing:
  output: true
  permalink: /services/ticketing/:title
  
 tours-and-travel:
  output: true
  permalink: /services/tours-and-travel/:title